version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"              # location of requirements*.txt files
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"              # location of workflow files
    schedule:
      interval: "weekly"
