name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    branches: [ "master" ]
    # Only run when relevant files change (no paths-ignore here)
    paths:
      - 'fuzz/**'
      - '**/*.py'
      - 'requirements*.txt'
      - 'Dockerfile'
      - 'dockerized_labs/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  fuzz:
    name: Build & run fuzzers
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: { sanitizer: [ address ] }
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1

      - name: Checkout (PR merge ref)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - name: Decide fuzzing mode
        id: mode
        shell: bash
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            base="${{ github.event.pull_request.base.sha }}"
            head="${{ github.event.pull_request.head.sha }}"
          else
            base="$(git rev-parse HEAD~1)"
            head="$(git rev-parse HEAD)"
          fi
          git fetch --no-tags --depth=1 origin "$base" || true
          if git diff --name-only "$base" "$head" | grep -E '^(fuzz/|.*\.py$)'; then
            echo "mode=code-change" >> "$GITHUB_OUTPUT"
          else
            echo "mode=batch" >> "$GITHUB_OUTPUT"
          fi
          echo "Chosen mode: $(grep mode= $GITHUB_OUTPUT | cut -d= -f2)"

      - name: Build fuzzers (${{ matrix.sanitizer }})
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1 pinned
        with:
          language: python
          sanitizer: ${{ matrix.sanitizer }}

      - name: Run fuzzers (${{ matrix.sanitizer }})
        continue-on-error: true     # ← don’t fail PR even if no targets found
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1 pinned
        with:
          fuzz-seconds: 600
          mode: ${{ steps.mode.outputs.mode }}
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true

      - name: Collect SARIF
        if: always()
        run: |
          mkdir -p sarif_out
          find "$GITHUB_WORKSPACE" -type f -name '*.sarif' -exec cp {} sarif_out/ \; || true

      - name: Upload SARIF artifact
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: cflite-pr-sarif
          path: sarif_out/
          if-no-files-found: ignore

  upload-sarif:
    name: Upload to code scanning
    needs: fuzz
    if: always()                 # run even if fuzz job had a soft failure
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Download SARIF (if any)
        id: dl
        continue-on-error: true  # don't fail if artifact is missing
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4 pinned
        with:
          name: cflite-pr-sarif
          path: sarif_in/

      - name: Find SARIF
        id: find
        if: steps.dl.outcome == 'success'
        run: |
          FILE="$(find sarif_in -type f -name '*.sarif' | head -n1 || true)"
          if [ -n "$FILE" ]; then echo "sarif=$FILE" >> "$GITHUB_OUTPUT"; fi

      - name: Upload SARIF
        if: steps.find.outputs.sarif
        uses: github/codeql-action/upload-sarif@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3.30.5
        with:
          sarif_file: ${{ steps.find.outputs.sarif }}
