name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    branches: [ "master" ]
    # Only run when code or fuzz targets change (skip docs/workflows)
    paths:
      - 'fuzz/**'
      - '**/*.py'
      - 'requirements*.txt'
      - 'Dockerfile'
      - 'dockerized_labs/**'
    paths-ignore:
      - '.github/**'
      - '**/*.md'
  workflow_dispatch: {}

# Least privilege by default
permissions:
  contents: read

jobs:
  fuzz:
    name: Build & run fuzzers
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [ address ]

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1

      - name: Build fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python
          sanitizer: ${{ matrix.sanitizer }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run fuzzers (${{ matrix.sanitizer }})
        id: run
        # Avoid red PRs when a change doesn’t touch fuzz targets.
        continue-on-error: true
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: code-change
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true

      - name: Upload fuzz artifacts (SARIF, logs)
        if: always() && hashFiles('results.sarif') != ''
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: cflite-${{ matrix.sanitizer }}-sarif
          path: |
            results.sarif
            findings/**
          if-no-files-found: ignore

  upload-sarif:
    name: Upload to code scanning
    needs: fuzz
    if: always() && hashFiles('**/results.sarif') != ''
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # scoped only to this job
    steps:
      - name: Download SARIF
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: cflite-address-sarif
          path: .
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3.30.5
        with:
          sarif_file: results.sarif
