name: Flake8

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

# Least privilege by default 
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PIP_REQUIRE_HASHES: "1"   # enforce hash-checked installs


    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          [ -f requirements.txt ] && pip install --require-hashes -r requirements.txt || true
          pip install --require-hashes -r requirements-dev.txt

      - name: Lint with flake8 (errors fail)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Lint with flake8 (warnings only)
        run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
