name: Generate hashed requirements

on:
  workflow_dispatch: {}  # manual trigger

permissions:
  contents: read

jobs:
  lock-deps:
    runs-on: ubuntu-latest
    # Needs to push a branch and open a PR
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: python -m pip install --upgrade pip pip-tools

      - name: Prepare inputs (preserve existing content)
        shell: bash
        run: |
          set -euo pipefail
          # If requirements.in is missing but requirements.txt exists, convert it.
          if [ ! -f requirements.in ] && [ -f requirements.txt ]; then
            mv requirements.txt requirements.in
          fi
          # Ensure requirements.in exists (empty is okay if starting fresh).
          if [ ! -f requirements.in ]; then
            : > requirements.in
          fi
          # Ensure dev input exists with basic tools if starting fresh.
          if [ ! -f requirements-dev.in ]; then
            printf "pytest\nflake8\n" > requirements-dev.in
          fi

      - name: Compile pinned + hashed files
        run: |
          pip-compile --generate-hashes --output-file requirements.txt requirements.in
          pip-compile --generate-hashes --output-file requirements-dev.txt requirements-dev.in

      - name: Create branch, commit, and push
        env:
          BRANCH: chore/hash-locked-reqs
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Make sure we know the remote state of the branch (if it already exists)
          git fetch --prune origin "$BRANCH" || true

          # Create/reset local branch from current commit
          git checkout -B "$BRANCH"

          git add requirements.in requirements.txt requirements-dev.in requirements-dev.txt
          if git diff --staged --quiet; then
            echo "No changes to commit."
            echo "skip_pr=true" >> "$GITHUB_ENV"
          else
            git commit -m "chore(deps): add hash-locked requirements via pip-tools"
            # Update the remote branch safely even if it already exists
            git push --force-with-lease --set-upstream origin "$BRANCH"
          fi

      - name: Open pull request
        if: env.skip_pr != 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create PR if it doesn't exist; otherwise just show it
          gh pr view chore/hash-locked-reqs --json url >/dev/null 2>&1 \
            || gh pr create \
                 --title "chore(deps): add hash-locked requirements via pip-tools" \
                 --body "Adds requirements.txt and requirements-dev.txt with --require-hashes for reproducible installs." \
                 --base master \
                 --head chore/hash-locked-reqs
          gh pr view chore/hash-locked-reqs --json url -q .url
