name: OSV scan

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  schedule:
    - cron: "30 12 * * 1"  # Mondays 12:30 UTC

permissions:
  contents: read

jobs:
  # PRs from same repo: scan ONLY core lockfiles + upload SARIF
  osv-pr:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
    permissions:
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@e92b5d07338d4f0ba0981dffed17c48976ca4730
    with:
      scan-args: >-
        --lockfile requirements.txt
        --lockfile requirements-dev.txt

  # Pushes & schedule: scan ONLY core lockfiles + upload SARIF
  osv-scheduled:
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@e92b5d07338d4f0ba0981dffed17c48976ca4730
    with:
      scan-args: >-
        --lockfile requirements.txt
        --lockfile requirements-dev.txt

  # Labs: JSON-only artifact (non-blocking, no SARIF)
  osv-labs-json:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4 pinned
      - name: OSV scan (labs JSON)
        continue-on-error: true
        uses: google/osv-scanner-action/osv-scanner-action@e92b5d07338d4f0ba0981dffed17c48976ca4730
        with:
          scan-args: >-
            --format json
            --output osv-labs-results.json
            --lockfile dockerized_labs/broken_auth_lab/requirements.lab.txt
            --lockfile dockerized_labs/insec_des_lab/requirements.lab.txt
            --lockfile dockerized_labs/sensitive_data_exposure/requirements.lab.txt
      - name: Upload labs JSON
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4 pinned
        with:
          name: osv-labs-results-json
          path: osv-labs-results.json
