name: OSV scan (labs only)

on:
  schedule:
    - cron: "15 3 * * 1"   # Mondays 03:15 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  labs:
    # Call the OSV reusable workflow at the job level (no runs-on, no steps)
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@e92b5d07338d4f0ba0981dffed17c48976ca4730
    with:
      # Scan only lab manifests; do not fail when vulns are found
      scan-args: >-
        --fail-on-vuln=false
        --lockfile dockerized_labs/broken_auth_lab/requirements.txt
        --lockfile dockerized_labs/insec_des_lab/requirements.txt
        --lockfile dockerized_labs/sensitive_data_exposure/requirements.txt
