name: OSV scan

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  schedule:
    - cron: "30 12 * * 1"  # Mondays 12:30 UTC

permissions:
  contents: read

jobs:
  # PR: scan ONLY core lockfiles, upload SARIF (same-repo PRs only)
  osv-pr:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@e92b5d07338d4f0ba0981dffed17c48976ca4730
    with:
      scan-args: >-
        --lockfile requirements.txt
        --lockfile requirements-dev.txt

  # Push/schedule: scan ONLY core lockfiles, upload SARIF
  osv-scheduled:
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@e92b5d07338d4f0ba0981dffed17c48976ca4730
    with:
      scan-args: >-
        --lockfile requirements.txt
        --lockfile requirements-dev.txt
